### ISSUE TITLE
Use restart policy to keep couchpotato "alive"

### ISSUE THREAD

**Issue by Ashex1** [razorgirl/docker-couchpotato#1]
Docker now has support for restart policies, when starting the container you will want to append --restart=always to keep it alive between restarts. 

https://docs.docker.com/reference/commandline/cli/#restart-policies

```
docker run -d -p 5050:5050 -v <LOCAL_MOVIES_FOLDER>:/movies --name couchpotato apps/couchpotato --restart=always
```

**Comment by razorgirl** [comment]
Thanks @Ashex1, I have added that to the README. I didn't know about that (rather recent) feature so thanks double for that.
