### ISSUE TITLE
No explicit license

### ISSUE THREAD

**Issue by cimnine** [razorgirl/docker-couchpotato#5]
It is currently legally unclear if you permit to remix and build up on your work. Therefore I ask you to add a license which would permit (or explicitly deny) this.

If you would like to permit it, http://choosealicense.com/ might be helpful if you are uncertain about licenses. If you don't care about what happens to this work of yours, you can release it to public domain. Some choices are http://unlicense.org/ or https://creativecommons.org/publicdomain/zero/1.0/ or http://www.wtfpl.net/about/.

Thanks,
Chris

**Comment by razorgirl** [comment]
This repo has been under Unlicense terms since day one. See README.md.

**Comment by cimnine** [comment]
Sry, I must have been blind that day. Thanks for the work & response!
